### ISSUE TITLE
Uvoz in poročilo

### ISSUE THREAD

**Issue by jaanos** [pdurcik/APPR-2017#1]
Pri uvozu podatkov (pa tudi sicer) podaj poti datotek relativno na vrhnji imenik projekta, npr.
```R
priseljeni <- read_csv("podatki/tabeladrzav.csv", col_names = stolpci,
                       skip = 1, na = ":", locale = locale(encoding = "cp1250"))
```

Svetujem še, da del poročila iz vzorca zaenkrat izbrišeš, da boš lahko prevedel poročilo. Lepši prikaz tabel dosežeš z ukazom `kable`, npr.
```R
kable(head(drzavljanstva)) # neposredni klic, ali
head(azil) %>% kable() # s pomočjo veriženja
```

**Comment by pdurcik** [comment]
Sem popravil kot ste napisali.

**Comment by jaanos** [comment]
V redu - če urediš zadevo, jo lahko sam zapreš s klikom na **Close issue** (ali **Close and comment**, če ob tem še kaj napišeš).

Še ena manjša pripomba: v poročilu postavi prazno vrstico pred sezname, da se ti bodo lepo prikazali ob prevajanju. Naslove za vire lahko pustiš brez \`\`, pa se bodo samodejno ustvarile povezave.
